openapi: 3.0.1
info:
  title: Ecomm Project
  version: 0.0.1
  contact:
    name: Customer Support
    email: nxtdev@example.com
servers:
- url: https://63d3e166c1ba499e54cb26a6.mockapi.io/
paths:
  /api/orders:
    post:
      summary: Registration of new Order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        201: 
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
        400:
          description: Order not Registrated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
  /api/orders/{id}:
    parameters: 
      - name: id
        in: path
        schema:
          type: string
        required: true
    get:
      summary: Retrive Orders
      responses:
        200:
          description: Sucess
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        404:
          description: Order not found
          content:
            application/json:
              example: "Bad Request"
components:
  schemas:
    Client:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    DeliveryAddress:
      type: object
      properties:
        street:
          type: string
        homeNumber:
          type: string
        complement:
          type: string
        zipCode:
          type: number
        city:
          type: string
        state:
          type: string
    Item:
      type: object
      properties:
        id: 
          type: string
        product:
          type: string
        quantity:
          type: number
        price:
          type: number
        discount:
          type: number
        finalPrice:
          type: number
    Items:
      type: array
      items:
        $ref: '#/components/schemas/Item'
    Order:
      type: object
      properties:
        client:
          $ref: '#/components/schemas/Client'
        deliveryAddress:
          $ref: '#/components/schemas/DeliveryAddress'
        items:
          $ref: '#/components/schemas/Items'
          
          
          
          
          
          