version: "3.9"
services:
  mongo:
    image: mongo:5
    restart: always
    container_name: mongo-ecomm
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
  mongo-seed:
    image: mongo:5
    container_name: mongo-seed
    links:
      - mongo
    volumes:
      - "./mongo-seed:/mongo-seed"
    command: /bin/bash "/mongo-seed/import.sh"
    depends_on:
      - mongo
  product:
    build: ./product
    container_name: ecomm-product
    ports:
      - 3000:3000
    depends_on:
      - mongo
  account:
    build: ./account
    container_name: ecomm-account
    ports:
      - 3001:3001
    depends_on:
      - mongo
  mysql:
    image: mysql
    container_name: mysql-ecomm
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
  finance:
    build: ./finance
    container_name: ecomm-finance
    ports:
      - 3003:3003
    depends_on:
      - mysql